# ===== SOFT PASTEL DARK REFINED =====

background #0F0F0F
foreground #E9D8A6

background_opacity 0.96
dynamic_background_opacity no
hide_window_decorations yes

selection_background #3AAEC9
selection_foreground #E9D8A6

cursor #94D2BD
cursor_text_color #002B36

# ANSI base
color0  #002B36
color1  #FA4B3C
color2  #0A9396
color3  #EE9B00
color4  #0A9396
color5  #CA6702
color6  #94D2BD
color7  #E9D8A6

# Bright
color8  #005F73
color9  #FA4B3C
color10 #94D2BD
color11 #CA6702
color12 #0A9396
color13 #EE9B00
color14 #94D2BD
color15 #FFFFFF


# ===== CONFIGURACIÓN DE LAYOUT =====
# Habilitar modo de división (necesario para splits)
enabled_layouts splits,stack


# ===== ATAJOS PARA DUPLICAR (MISMA RUTA) =====
# Ctrl + Shift + N: Divide la pantalla verticalmente al 50%
map ctrl+shift+n launch --location=vsplit --cwd=current

# Ctrl + Shift + T: Nueva pestaña en la misma ruta
map ctrl+shift+t launch --current --type=tab --cwd=current


# ===== NAVEGACIÓN ENTRE PANELES CON ALT =====
# Moverse entre las mitades usando Alt + Flechas
map alt+left neighboring_window left
map alt+right neighboring_window right

# Maximizar y restablecer
map super+up    toggle_maximized
# Minimizar (ocultar la ventana)
map super+down  hide_window
