# ===== SOFT PASTEL DARK REFINED =====

background #0B0B0C
foreground #F2E9E4

background_opacity 0.96
dynamic_background_opacity no
hide_window_decorations yes

selection_background #EDE0D4
selection_foreground #1B1B1D

cursor #94D2BD
cursor_text_color #222124

# ANSI (más neutro y profundo)
color0  #1B1B1D
color1  #D62828
color2  #2A9D8F
color3  #EE9B00
color4  #5FA8D3
color5  #B56576
color6  #94D2BD
color7  #EDE0D4

# Bright
color8  #4A4A4D
color9  #E76F51
color10 #2EC4B6
color11 #FFB703
color12 #8ECAE6
color13 #F28482
color14 #ADE8F4
color15 #FFFFFF


# ===== CONFIGURACIÓN DE LAYOUT =====
# Habilitar modo de división (necesario para splits)
enabled_layouts splits,stack


# ===== ATAJOS PARA DUPLICAR (MISMA RUTA) =====
# Ctrl + Shift + N: Divide la pantalla verticalmente al 50%
map ctrl+shift+n launch --location=vsplit --cwd=current

# Ctrl + Shift + T: Nueva pestaña en la misma ruta
map ctrl+shift+t launch --current --type=tab --cwd=current


# ===== NAVEGACIÓN ENTRE PANELES CON ALT =====
# Moverse entre las mitades usando Alt + Flechas
map alt+left neighboring_window left
map alt+right neighboring_window right

# Maximizar y restablecer
map super+up    toggle_maximized
# Minimizar (ocultar la ventana)
map super+down  hide_window

